/**
 * MASTER NETFLIX CATALOG - 2026 AUTHENTIC EDITION
 * Pixel-perfect alignment with live Netflix India UI hierarchy,
 * dynamic badge metadata, and verified high-res local & CDN assets.
 */

const MASTER_CATALOG = {
  hero: {
    id: 289456,
    title: "Teach You A Lesson",
    heroTitleUpper: "S E R I E S",
    heroTitleLower: "TEACH YOU A LESSON",
    subtitleTags: "Series • Drama • 2026 • Limited Series • A",
    type: "tv",
    overview: "When bullies take over schools, special inspectors step in to teach them a lesson in this action comedy that reached Top 10 Shows in over 48 countries.",
    posterUrl: "/assets/exact/teach_you_lesson_hero.jpg",
    backdropUrl: "/assets/exact/teach_you_lesson_hero.jpg",
    rating: 9.1,
    badge: "Limited Series • Action • 2026 • A",
    matchPercentage: "99% Match",
    maturityRating: "A",
    duration: "Limited Series",
    year: "2026",
    audioQuality: "DOLBY ATMOS",
    videoQuality: "4K ULTRA HD",
    tenureText: "Spent 11 weeks in the Top 10",
    genres: ["Action", "School Drama", "Comedy"],
    cast: ["Kim Mu-yeol", "Lee Sung-min", "Jin Ki-joo", "Pyo Ji-hoon"],
    director: "Yong-taek Chae"
  },
  categories: [
    { id: "all", label: "Home" },
    { id: "tv", label: "Shows" },
    { id: "movie", label: "Movies" },
    { id: "games", label: "Games" },
    { id: "new", label: "New & Popular" },
    { id: "mylist", label: "My List" },
    { id: "languages", label: "Browse by Languages" }
  ],
  notifications: [
    {
      id: 1,
      title: "New Episodes Live",
      message: "Chumbak has dropped new episodes! Watch now in HD.",
      time: "20m ago",
      thumb: "/assets/exact/chumbak.jpg"
    },
    {
      id: 2,
      title: "#1 Movie in India",
      message: "Vishwanath & Sons is trending #1 in Movies across India today.",
      time: "1 hour ago",
      thumb: "/assets/exact/top10_1_vishwanath.jpg"
    },
    {
      id: 3,
      title: "New Season Dropped",
      message: "The Gentlemen Season 2 is now streaming globally.",
      time: "3 hours ago",
      thumb: "/assets/exact/gentlemen.jpg"
    },
    {
      id: 4,
      title: "Global Hit",
      message: "Teach You A Lesson reaches the Top 10 in over 48 countries.",
      time: "5 hours ago",
      thumb: "/assets/exact/teach_you_lesson_hero.jpg"
    }
  ],
  rows: [
    {
      id: "top_10_movies_india",
      title: "Top 10 Movies in India Today",
      isTop10: true,
      items: [
        {
          id: 1408162,
          rank: 1,
          isTop10: true,
          title: "Vishwanath & Sons",
          type: "movie",
          posterUrl: "/assets/exact/top10_1_vishwanath.jpg",
          backdropUrl: "/assets/exact/vishwanath_and_sons.jpg",
          badgeType: "recently_added",
          maturityRating: "U/A 13+",
          duration: "2h 15m",
          matchPercentage: "99% Match",
          quality: "4K ULTRA HD",
          genres: ["Drama", "Family"],
          overview: "A heartwarming multi-generational family drama celebrating tradition and modern aspirations."
        },
        {
          id: 1489543,
          rank: 2,
          isTop10: true,
          title: "G.D.N",
          type: "movie",
          posterUrl: "/assets/exact/top10_3_gdn.jpg",
          backdropUrl: "/assets/exact/gdn.jpg",
          badgeType: "recently_added",
          maturityRating: "U/A 16+",
          duration: "2h 24m",
          matchPercentage: "98% Match",
          quality: "4K ULTRA HD",
          genres: ["Action", "Thriller"],
          overview: "A gripping espionage thriller following an operative navigating high-stakes political intrigue."
        },
        {
          id: 1512401,
          rank: 3,
          isTop10: true,
          title: "Dhamaal 4",
          type: "movie",
          posterUrl: "/assets/exact/top10_2_dhamaal_4.jpg",
          backdropUrl: "/assets/exact/early_spring.jpg",
          badgeType: "recently_added",
          maturityRating: "U/A 7+",
          duration: "2h 10m",
          matchPercentage: "97% Match",
          quality: "4K ULTRA HD",
          genres: ["Comedy", "Adventure"],
          overview: "The beloved comedic crew returns for an outrageous treasure hunt full of crazy mishaps."
        },
        {
          id: 1355228,
          rank: 4,
          isTop10: true,
          title: "Guns & Gulaabs",
          type: "tv",
          posterUrl: "/assets/exact/top10_4_gandhari.jpg",
          backdropUrl: "/assets/exact/gandhari_popover.jpg",
          badgeType: "recently_added",
          maturityRating: "U/A 16+",
          duration: "7 Episodes",
          matchPercentage: "99% Match",
          quality: "4K ULTRA HD",
          genres: ["Offbeat", "Exciting", "Thriller"],
          overview: "In the cartel-run town of Gulaabganj, an unprecedented opium deal pulls a big-city cop and a lovesick mechanic into chaos."
        },
        {
          id: 1478902,
          rank: 5,
          isTop10: true,
          title: "Korean Kanakaraju",
          type: "movie",
          posterUrl: "/assets/exact/top10_5_korean_kanakaraju.jpg",
          backdropUrl: "/assets/exact/strong_girl_nam_soon.jpg",
          badgeType: "recently_added",
          maturityRating: "U/A 16+",
          duration: "2h 18m",
          matchPercentage: "95% Match",
          quality: "4K ULTRA HD",
          genres: ["Action", "Comedy"],
          overview: "A daring cross-cultural action adventure set across Seoul and South India."
        },
        {
          id: 857598,
          rank: 6,
          isTop10: true,
          title: "Pushpa 2: The Rule",
          type: "movie",
          posterUrl: "https://image.tmdb.org/t/p/w500/1T21FblunT0y8fz7YaW8JMYgUKm.jpg",
          backdropUrl: "https://image.tmdb.org/t/p/original/5nEyyLkElpD7zkqh41aSkTCchcc.jpg",
          badgeType: "recently_added",
          maturityRating: "U/A 16+",
          duration: "3h 20m",
          matchPercentage: "99% Match",
          quality: "4K ULTRA HD",
          genres: ["Action", "Crime", "Thriller"],
          overview: "Pushpa Raj expands his syndicate rule across borders in this massive action blockbuster."
        },
        {
          id: 801688,
          rank: 7,
          isTop10: true,
          title: "Kalki 2898 AD",
          type: "movie",
          posterUrl: "https://image.tmdb.org/t/p/w500/rstcAnBeCkxNQjNp3YXrF6IP1tW.jpg",
          backdropUrl: "https://image.tmdb.org/t/p/original/o8XSR1SONnjcsv84NRu6Mwsl5io.jpg",
          badgeType: "recently_added",
          maturityRating: "U/A 13+",
          duration: "3h 1m",
          matchPercentage: "98% Match",
          quality: "4K ULTRA HD",
          genres: ["Sci-Fi", "Action"],
          overview: "Immortal warriors clash in a battle spanning millennia in a breathtaking dystopian saga."
        },
        {
          id: 811941,
          rank: 8,
          isTop10: true,
          title: "Devara: Part 1",
          type: "movie",
          posterUrl: "https://image.tmdb.org/t/p/w500/lQfuaXjANoTsdx5iS0gCXlK9D2L.jpg",
          backdropUrl: "https://image.tmdb.org/t/p/original/hAQnXxOwCjgYcKRgTdYPRC8neqL.jpg",
          badgeType: "recently_added",
          maturityRating: "U/A 16+",
          duration: "2h 58m",
          matchPercentage: "97% Match",
          quality: "4K ULTRA HD",
          genres: ["Action", "Drama"],
          overview: "A fearless coastal warrior fights to safeguard his people from deceitful syndicates."
        },
        {
          id: 1171099,
          rank: 9,
          isTop10: true,
          title: "Maharaj",
          type: "movie",
          posterUrl: "https://image.tmdb.org/t/p/w500/lsuUGtUzrzEnlIUjVRSqFNUMZEz.jpg",
          backdropUrl: "https://image.tmdb.org/t/p/original/9RdDCAdZ8PL2qo6pJGRU1vY0UYj.jpg",
          badgeType: "recently_added",
          maturityRating: "U/A 16+",
          duration: "2h 11m",
          matchPercentage: "97% Match",
          quality: "4K ULTRA HD",
          genres: ["Drama", "History"],
          overview: "In pre-independence India, a courageous journalist takes on an influential leader for truth."
        },
        {
          id: 1086729,
          rank: 10,
          isTop10: true,
          title: "Amar Singh Chamkila",
          type: "movie",
          posterUrl: "https://image.tmdb.org/t/p/w500/t9wSGgaPfbGUBBlne7xw8GaArvu.jpg",
          backdropUrl: "https://image.tmdb.org/t/p/original/qh7PWKRfy2K8rZZP7LzembGgWIU.jpg",
          badgeType: "recently_added",
          maturityRating: "U/A 16+",
          duration: "2h 25m",
          matchPercentage: "99% Match",
          quality: "4K ULTRA HD",
          genres: ["Music", "Biography"],
          overview: "The electrifying story of Punjab's folk sensation whose daring music captivated millions."
        }
      ]
    },
    {
      id: "top_10_shows_india",
      title: "Top 10 Shows in India Today",
      isTop10: true,
      items: [
        {
          id: 313172,
          rank: 1,
          isTop10: true,
          title: "Chumbak",
          type: "tv",
          posterUrl: "/assets/exact/chumbak.jpg",
          backdropUrl: "/assets/exact/chumbak.jpg",
          badgeType: "dual_episode",
          hasNewEpisode: true,
          maturityRating: "U/A 16+",
          duration: "2 Seasons",
          matchPercentage: "99% Match",
          quality: "4K ULTRA HD",
          genres: ["Drama", "Comedy"],
          overview: "An unexpected encounter brings together two contrasting souls on an unforgettable emotional journey."
        },
        {
          id: 300507,
          rank: 2,
          isTop10: true,
          title: "Crew Girl",
          type: "tv",
          posterUrl: "/assets/exact/crew_girl.jpg",
          backdropUrl: "/assets/exact/crew_girl.jpg",
          badgeType: "recently_added",
          maturityRating: "U/A 16+",
          duration: "1 Season",
          matchPercentage: "97% Match",
          quality: "4K ULTRA HD",
          genres: ["Drama", "Romance"],
          overview: "Behind the glamorous world of aviation lies a turbulent realm of ambition, friendship, and secrets."
        },
        {
          id: 289104,
          rank: 3,
          isTop10: true,
          title: "Operation Safed Sagar",
          type: "tv",
          posterUrl: "https://image.tmdb.org/t/p/w500/u8b8sdWzzvAIKjTBGh9aCio6hU6.jpg",
          backdropUrl: "https://image.tmdb.org/t/p/original/fzq5QiEtx8MCtQ4yTZzWbJHnstr.jpg",
          badgeType: "recently_added",
          maturityRating: "U/A 16+",
          duration: "1 Season",
          matchPercentage: "98% Match",
          quality: "4K ULTRA HD",
          genres: ["War", "Action", "History"],
          overview: "The heroic true accounts of Indian Air Force fighter pilots executing surgical mountain strikes."
        },
        {
          id: 262838,
          rank: 4,
          isTop10: true,
          title: "India's Got Latent",
          type: "tv",
          posterUrl: "/assets/exact/indias_got_latent.jpg",
          backdropUrl: "/assets/exact/indias_got_latent.jpg",
          badgeType: "recently_added",
          maturityRating: "A",
          duration: "1 Season",
          matchPercentage: "99% Match",
          quality: "4K ULTRA HD",
          genres: ["Comedy", "Reality"],
          overview: "Comedian Samay Raina hosts India's rawest and most hilarious talent and comedy showcase."
        },
        {
          id: 236235,
          rank: 5,
          isTop10: true,
          title: "The Gentlemen",
          type: "tv",
          posterUrl: "/assets/exact/gentlemen.jpg",
          backdropUrl: "https://image.tmdb.org/t/p/original/yG1wltFmkX5c5ocACKfpX0tp3SY.jpg",
          badgeType: "new_season",
          maturityRating: "A",
          duration: "2 Seasons",
          matchPercentage: "98% Match",
          quality: "4K ULTRA HD",
          genres: ["Action", "Crime", "Comedy"],
          overview: "An aristocratic heir unexpectedly inherits a sprawling weed empire, entering a violent London criminal underworld."
        },
        {
          id: 289456,
          rank: 6,
          isTop10: true,
          title: "Teach You A Lesson",
          type: "tv",
          posterUrl: "/assets/exact/teach_you_lesson_hero.jpg",
          backdropUrl: "/assets/exact/teach_you_lesson_hero.jpg",
          badgeType: "recently_added",
          maturityRating: "A",
          duration: "Limited Series",
          matchPercentage: "99% Match",
          quality: "4K ULTRA HD",
          genres: ["Action", "School Drama"],
          overview: "When school authority crumbles, fearless educational inspectors intervene to enforce discipline."
        },
        {
          id: 93405,
          rank: 7,
          isTop10: true,
          title: "Squid Game",
          type: "tv",
          posterUrl: "https://image.tmdb.org/t/p/w500/1QdXdRYfktUSONkl1oD5gc6Be0s.jpg",
          backdropUrl: "https://image.tmdb.org/t/p/original/2meX1nMdScFOoV4370rqHWKmXhY.jpg",
          badgeType: "new_season",
          maturityRating: "U/A 16+",
          duration: "2 Seasons",
          matchPercentage: "99% Match",
          quality: "4K ULTRA HD",
          genres: ["Thriller", "Drama"],
          overview: "Player 456 enters the deadly arena once again to dismantle the organization from within."
        },
        {
          id: 247769,
          rank: 8,
          isTop10: true,
          title: "The Great Indian Kapil Show",
          type: "tv",
          posterUrl: "https://image.tmdb.org/t/p/w500/3KMCmGDlYLlJ8zGOhCs6f3FZcnj.jpg",
          backdropUrl: "https://image.tmdb.org/t/p/original/w8L2oVjsSRZdZ1Wcszot9cKZMRO.jpg",
          badgeType: "dual_episode",
          hasNewEpisode: true,
          maturityRating: "U/A 13+",
          duration: "2 Seasons",
          matchPercentage: "98% Match",
          quality: "4K ULTRA HD",
          genres: ["Comedy", "Talk Show"],
          overview: "Kapil Sharma and his eccentric cast host India's biggest Bollywood stars in a laughter-packed show."
        },
        {
          id: 129552,
          rank: 9,
          isTop10: true,
          title: "The Night Agent",
          type: "tv",
          posterUrl: "https://image.tmdb.org/t/p/w500/4c5yUNcaff4W4aPrkXE6zr7papX.jpg",
          backdropUrl: "https://image.tmdb.org/t/p/original/gklrevVndG98GHGDwfm8y8kxESo.jpg",
          badgeType: "new_season",
          maturityRating: "U/A 16+",
          duration: "2 Seasons",
          matchPercentage: "97% Match",
          quality: "4K ULTRA HD",
          genres: ["Action", "Thriller"],
          overview: "A basement telephone rings, thrusting a dedicated FBI agent into a conspiracy reaching the White House."
        },
        {
          id: 156716,
          rank: 10,
          isTop10: true,
          title: "Heeramandi: The Diamond Bazaar",
          type: "tv",
          posterUrl: "https://image.tmdb.org/t/p/w500/uSmnvWK3bCPz87jkE0GpZsMnYpT.jpg",
          backdropUrl: "https://image.tmdb.org/t/p/original/z0F11p7HBaIUizZHGzyZ32FLm7O.jpg",
          badgeType: "recently_added",
          maturityRating: "U/A 16+",
          duration: "1 Season",
          matchPercentage: "95% Match",
          quality: "4K ULTRA HD",
          genres: ["Drama", "Historical"],
          overview: "A grand epic chronicling love, betrayal, and freedom in pre-partition Lahore's famous courtesan houses."
        }
      ]
    },
    {
      id: "trending_shows_showcase",
      title: "Popular TV Shows in India",
      isLandscape: true,
      items: [
        {
          id: 313172,
          title: "Chumbak",
          type: "tv",
          posterUrl: "/assets/exact/chumbak.jpg",
          backdropUrl: "/assets/exact/chumbak.jpg",
          isTop10Badge: true,
          badgeType: "dual_episode",
          hasNewEpisode: true,
          maturityRating: "U/A 16+",
          duration: "2 Seasons",
          matchPercentage: "99% Match",
          genres: ["Drama", "Comedy"]
        },
        {
          id: 1408162,
          title: "Vishwanath & Sons",
          type: "movie",
          posterUrl: "/assets/exact/top10_1_vishwanath.jpg",
          backdropUrl: "/assets/exact/vishwanath_and_sons.jpg",
          isTop10Badge: true,
          badgeType: "recently_added",
          maturityRating: "U/A 13+",
          duration: "2h 15m",
          matchPercentage: "99% Match",
          genres: ["Family", "Drama"]
        },
        {
          id: 289190,
          title: "Hustle 5",
          type: "tv",
          posterUrl: "/assets/exact/early_spring.jpg",
          backdropUrl: "/assets/exact/early_spring.jpg",
          badgeType: "dual_episode",
          hasNewEpisode: true,
          maturityRating: "U/A 16+",
          duration: "5 Seasons",
          matchPercentage: "98% Match",
          genres: ["Music", "Reality"]
        },
        {
          id: 67341,
          title: "FAUDA",
          type: "tv",
          posterUrl: "/assets/exact/fauda_popover.jpg",
          backdropUrl: "/assets/exact/fauda_popover.jpg",
          isTop10Badge: true,
          badgeType: "new_season",
          maturityRating: "A",
          duration: "4 Seasons",
          matchPercentage: "97% Match",
          genres: ["Action", "Thriller"]
        },
        {
          id: 290123,
          title: "WWE RAW",
          type: "tv",
          posterUrl: "/assets/exact/wwe_raw.jpg",
          backdropUrl: "/assets/exact/wwe_raw.jpg",
          badgeType: "live",
          maturityRating: "U/A 16+",
          duration: "Live",
          matchPercentage: "96% Match",
          genres: ["Sports", "Action"]
        },
        {
          id: 236235,
          title: "The Gentlemen",
          type: "tv",
          posterUrl: "/assets/exact/gentlemen.jpg",
          backdropUrl: "https://image.tmdb.org/t/p/original/yG1wltFmkX5c5ocACKfpX0tp3SY.jpg",
          badgeType: "new_season",
          maturityRating: "A",
          duration: "2 Seasons",
          matchPercentage: "98% Match",
          genres: ["Crime", "Comedy"]
        }
      ]
    },
    {
      id: "crime_tv_thrillers",
      title: "Crime TV Thrillers",
      items: [
        {
          id: 71446,
          title: "Money Heist",
          type: "tv",
          posterUrl: "https://image.tmdb.org/t/p/w500/reEMJA1uzscCbk5r6Hyd16846um.jpg",
          backdropUrl: "https://image.tmdb.org/t/p/original/gFZriCkpJYsApPZEF3jhxL4yLzG.jpg",
          maturityRating: "A",
          duration: "5 Seasons",
          matchPercentage: "99% Match",
          genres: ["Crime", "Thriller", "Action"]
        },
        {
          id: 291456,
          title: "Taskaree: The Smuggler's War",
          type: "tv",
          posterUrl: "https://image.tmdb.org/t/p/w500/5a91Z9oO4fM0sFf4kU1xZ5r0qM3.jpg",
          backdropUrl: "https://image.tmdb.org/t/p/original/5LtSjMNw6j3LkG29Oa4O0iY5U8.jpg",
          isTop10Badge: true,
          maturityRating: "U/A 16+",
          duration: "1 Season",
          matchPercentage: "96% Match",
          genres: ["Action", "Crime"]
        },
        {
          id: 86831,
          title: "Delhi Crime",
          type: "tv",
          posterUrl: "https://image.tmdb.org/t/p/w500/eebUPRI4Z5e1Z7Hev4JZAwMIFkX.jpg",
          backdropUrl: "https://image.tmdb.org/t/p/original/6RV2o8PBCEyw9ylOWViV1CtULIF.jpg",
          maturityRating: "A",
          duration: "2 Seasons",
          matchPercentage: "98% Match",
          genres: ["Crime", "Drama"]
        },
        {
          id: 289412,
          title: "Dabba Cartel",
          type: "tv",
          posterUrl: "https://image.tmdb.org/t/p/w500/uSmnvWK3bCPz87jkE0GpZsMnYpT.jpg",
          backdropUrl: "https://image.tmdb.org/t/p/original/z0F11p7HBaIUizZHGzyZ32FLm7O.jpg",
          maturityRating: "U/A 16+",
          duration: "1 Season",
          matchPercentage: "95% Match",
          genres: ["Drama", "Crime"]
        },
        {
          id: 97576,
          title: "Jamtara: Sabka Number Aayega",
          type: "tv",
          posterUrl: "https://image.tmdb.org/t/p/w500/fMBookmwL6HjIgIVTjQ6EMr3pCH.jpg",
          backdropUrl: "https://image.tmdb.org/t/p/original/mQEmKXSFlzBlSoYgut0VfjxAzoA.jpg",
          maturityRating: "A",
          duration: "2 Seasons",
          matchPercentage: "97% Match",
          genres: ["Crime", "Drama"]
        }
      ]
    },
    {
      id: "because_you_watched_dangal",
      title: "Because you watched Dangal",
      items: [
        {
          id: 383827,
          title: "Sultan",
          type: "movie",
          posterUrl: "https://image.tmdb.org/t/p/w500/jFt1gS4BGHlK8xt76Y81Alp4dbt.jpg",
          backdropUrl: "https://image.tmdb.org/t/p/original/5LtSjMNw6j3LkG29Oa4O0iY5U8.jpg",
          maturityRating: "U/A 13+",
          duration: "2h 50m",
          matchPercentage: "97% Match",
          genres: ["Action", "Drama", "Sport"]
        },
        {
          id: 48988,
          title: "Chak De! India",
          type: "movie",
          posterUrl: "https://image.tmdb.org/t/p/w500/eebUPRI4Z5e1Z7Hev4JZAwMIFkX.jpg",
          backdropUrl: "https://image.tmdb.org/t/p/original/6RV2o8PBCEyw9ylOWViV1CtULIF.jpg",
          maturityRating: "U/A 7+",
          duration: "2h 33m",
          matchPercentage: "99% Match",
          genres: ["Drama", "Sport"]
        },
        {
          id: 10757,
          title: "Kabhi Khushi Kabhie Gham",
          type: "movie",
          posterUrl: "https://image.tmdb.org/t/p/w500/yXt07MYeiyQRzS69PMHy0BPjCGP.jpg",
          backdropUrl: "https://image.tmdb.org/t/p/original/uUVXEEyMsyWxrcbmAppUCYg6egV.jpg",
          maturityRating: "U/A 7+",
          duration: "3h 30m",
          matchPercentage: "98% Match",
          genres: ["Drama", "Romance", "Musical"]
        },
        {
          id: 872906,
          title: "Jawan (Extended Cut)",
          type: "movie",
          posterUrl: "https://image.tmdb.org/t/p/w500/jFt1gS4BGHlK8xt76Y81Alp4dbt.jpg",
          backdropUrl: "https://image.tmdb.org/t/p/original/5LtSjMNw6j3LkG29Oa4O0iY5U8.jpg",
          maturityRating: "U/A 16+",
          duration: "2h 56m",
          matchPercentage: "99% Match",
          genres: ["Action", "Thriller"]
        },
        {
          id: 509968,
          title: "Sui Dhaaga: Made in India",
          type: "movie",
          posterUrl: "https://image.tmdb.org/t/p/w500/yXt07MYeiyQRzS69PMHy0BPjCGP.jpg",
          backdropUrl: "https://image.tmdb.org/t/p/original/yNGAfRd0VZwtSAZiC1WXWqCbvIb.jpg",
          maturityRating: "U/A 13+",
          duration: "2h 2m",
          matchPercentage: "96% Match",
          genres: ["Drama", "Comedy"]
        }
      ]
    }
  ],
  games: [
    {
      id: 9001,
      title: "Stranger Things: 1984",
      type: "game",
      posterUrl: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
      badge: "Mobile Game • Adventure",
      rating: 9.0,
      matchPercentage: "98% Match",
      genres: ["Adventure", "Retro", "Pixel"]
    },
    {
      id: 9002,
      title: "Squid Game: Unleashed",
      type: "game",
      posterUrl: "https://image.tmdb.org/t/p/w500/1QdXdRYfktUSONkl1oD5gc6Be0s.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/2meX1nMdScFOoV4370rqHWKmXhY.jpg",
      badge: "Mobile Game • Action • 2026",
      rating: 9.3,
      matchPercentage: "99% Match",
      genres: ["Action", "Multiplayer", "Battle Royale"]
    }
  ]
};

module.exports = MASTER_CATALOG;
